FORMAT: 1A
HOST: https://rocky-hamlet-97078.herokuapp.com

# My Shorty

My Shorty is a quick, simple url shortener.

## Shortcode [/]

### Create Shortcode [POST /shorten]

You may create your own shortcode using this action. It takes a JSON
object containing an URL and a preferred shortcode.

+ Request (application/json)

    + Attributes (object)
        
        + url (string, required) - The url that the shortcode will point to
        + shortcode (string) - If informed, it will try to register this as
        the shortcode. It must respect the *^[0-9a-zA-Z_]{4,}$* pattern
            
    

+ Response 201 (application/json)
    
    + Attributes (object)
        
        + shortcode (string) - The returned shortcode
    
    + Body
        
            {"shortcode":"example_shortcode"}

+ Response 400 (text/html)
    
        Url is not present.

+ Response 409 (text/html)

        Shortcode already taken.


+ Response 422 (text/html)

        Invalid shortcode.

### Redirect to URL [GET /{shortcode}]

You will be redirected for the shortcode associated URL

+ Parameters

    + shortcode (string) - shortcode to get associated URL


+ Response 302 (text/html)

    + Header

            Location: http://shortcode_associated_url.com

+ Response 404 (text/html)

            Shortcode not found.

### Show Statistics [GET /{shortcode}/stats]

Return the statistics for the shortcode

+ Parameters

    + shortcode (string) - shortcode to get associated URL

+ Response 200 (application/json)
        
    + Attributes (object)
    
        + startDate (string)    - Date of inclusion of the shortcode (ISO8601)
        + redirectCount (number) - Number of times that the shortcode was used.
        + lastSeenDate (string) - Last time that the shortcode was used (ISO8601). This key will not be present if redirectCount == 0
    
    + Body
        
            {"startDate":"2016-08-14T17:11:09+00:00","redirectCount":1,"lastSeenDate":"2016-08-14T17:11:20+00:00"}


+ Response 404 (text/html)

            Shortcode not found.